"""Domain models, enums, and typed errors."""

from image_translator.domain.errors import (
    CheckpointError,
    DomainError,
    ExportBlockedError,
    ImageLoadError,
    InvalidRegionError,
    ProviderCallError,
    ProviderConfigError,
    QualityGateRejected,
    ReadingOrderUncertainError,
    RevisionPlanRejected,
    TranslationResultMismatchError,
    WorkflowCancelled,
)
from image_translator.domain.geometry import Point, Polygon, RegionGeometry, RotatedBoundingBox
from image_translator.domain.ids import (
    JobId,
    PageId,
    ProjectId,
    ProviderRequestId,
    RegionId,
    RevisionId,
    WorkflowThreadId,
)
from image_translator.domain.job import JobDefinition, JobSnapshot, JobStatus
from image_translator.domain.ocr import (
    NormalizedTextRegion,
    OCRCandidate,
    RawOCRRegion,
    ReadingOrder,
    ReadingOrderCandidate,
    TextOrientation,
    TextRole,
    WritingMode,
)
from image_translator.domain.quality import (
    QualityIssue,
    QualitySeverity,
    RegionReview,
    RubricScores,
)
from image_translator.domain.translation import (
    TranslationCandidate,
    TranslationRequest,
    TranslationResult,
)

__all__ = [
    "CheckpointError",
    "DomainError",
    "ExportBlockedError",
    "ImageLoadError",
    "InvalidRegionError",
    "JobDefinition",
    "JobId",
    "JobSnapshot",
    "JobStatus",
    "NormalizedTextRegion",
    "OCRCandidate",
    "PageId",
    "Point",
    "Polygon",
    "ProjectId",
    "ProviderCallError",
    "ProviderConfigError",
    "ProviderRequestId",
    "QualityGateRejected",
    "QualityIssue",
    "QualitySeverity",
    "RawOCRRegion",
    "ReadingOrder",
    "ReadingOrderCandidate",
    "ReadingOrderUncertainError",
    "RegionGeometry",
    "RegionId",
    "RegionReview",
    "RevisionId",
    "RevisionPlanRejected",
    "RotatedBoundingBox",
    "RubricScores",
    "TextOrientation",
    "TextRole",
    "TranslationCandidate",
    "TranslationRequest",
    "TranslationResult",
    "TranslationResultMismatchError",
    "WorkflowCancelled",
    "WorkflowThreadId",
    "WritingMode",
]
